#!/usr/bin/env bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z ${REGISTRY_USERNAME+x} ]
then
  export REGISTRY_USERNAME
  REGISTRY_USERNAME="$(lpass show 'Shared-Garden/cf-garden-docker' --username)"
  export REGISTRY_PASSWORD
  REGISTRY_PASSWORD="$(lpass show 'Shared-Garden/cf-garden-docker' --password)"
fi

(
  cd "$( dirname "$DIR" )"
  ginkgo -r -keepGoing -failOnPending -randomizeAllSpecs -randomizeSuites -p "$@"
)
