#!/usr/bin/env bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function print_usage() {
  echo "Usage: scripts/test [--skip-private-docker-registry-tests] [-- [ginkgo_args]]"
}

function set_default_groot_env() {
  if command -v get-groot-env.sh > /dev/null; then
    eval "$(get-groot-env.sh)" > /dev/null
  fi
}

while [ ! $# -eq 0 ]; do
  case "$1" in
    --skip-private-docker-registry-tests)
        export SKIP_PRIVATE_DOCKER_REGISTRY_TESTS=true
      ;;

    --)
      shift
      break
      ;;

    --help | -h)
      print_usage
      exit 0
      ;;
  esac
  shift
done

(
  cd "$( dirname "$DIR" )"
  if [ -z ${REGISTRY_USERNAME+x} ]; then
    set_default_groot_env
  fi
  ginkgo -r -keepGoing -failOnPending -randomizeAllSpecs -randomizeSuites -p "$@"
)
